CREATE VIEW CLIENTES_GLOBAL
AS
  SELECT
    E7SUCURSAL.NOMBRE AS SUCURSAL,
    E7CLIENTE.NOMBRE,
    E7CLIENTE.TELEFONO
  FROM E7CLIENTE@CDMX, E7SUCURSAL@CDMX
  WHERE E7CLIENTE.SUCURSAL_ID = E7SUCURSAL.ID
  UNION
  SELECT
    E7SUCURSAL.NOMBRE AS SUCURSAL,
    E7CLIENTE.NOMBRE,
    E7CLIENTE.TELEFONO
  FROM E7CLIENTE@P_QRO, E7SUCURSAL@P_QRO
  WHERE E7CLIENTE.SUCURSAL_ID = E7SUCURSAL.ID
  UNION
  SELECT
    E7SUCURSAL.NOMBRE AS SUCURSAL,
    E7CLIENTE.NOMBRE,
    E7CLIENTE.TELEFONO
  FROM E7CLIENTE@SLP, E7SUCURSAL@SLP
  WHERE E7CLIENTE.SUCURSAL_ID = E7SUCURSAL.ID
