CREATE VIEW INVENTARIO_PRODUCTOS_GLOBAL
  AS
SELECT
  E7SUCURSAL.NOMBRE AS SUCURSAL,
  E7INVENTARIO.ITEM_ID AS ID,
  E7INVENTARIO.CANTIDAD,
  E7PRODUCTO.NOMBRE
FROM E7INVENTARIO@CDMX, E7PRODUCTO@CDMX, E7SUCURSAL@CDMX
WHERE E7INVENTARIO.TIPO_ITEM = 'R'
      AND E7PRODUCTO.ID = E7INVENTARIO.ITEM_ID
UNION
SELECT
  E7SUCURSAL.NOMBRE,
  E7INVENTARIO.ITEM_ID AS ID,
  E7INVENTARIO.CANTIDAD,
  E7PRODUCTO.NOMBRE
FROM E7INVENTARIO@P_QRO, E7PRODUCTO@P_QRO, E7SUCURSAL@P_QRO
WHERE E7INVENTARIO.TIPO_ITEM = 'R'
      AND E7PRODUCTO.ID = E7INVENTARIO.ITEM_ID
      AND E7SUCURSAL.ID = E7INVENTARIO.SUCURSAL_ID AND E7SUCURSAL.ID = E7INVENTARIO.SUCURSAL_ID
UNION
SELECT
  E7SUCURSAL.NOMBRE,
  E7INVENTARIO.ITEM_ID AS ID,
  E7INVENTARIO.CANTIDAD,
  E7PRODUCTO.NOMBRE
FROM E7INVENTARIO@SLP, E7PRODUCTO@SLP, E7SUCURSAL@SLP
WHERE E7INVENTARIO.TIPO_ITEM = 'R'
      AND E7PRODUCTO.ID = E7INVENTARIO.ITEM_ID
      AND E7SUCURSAL.ID = E7INVENTARIO.SUCURSAL_ID;
