CREATE VIEW INVENTARIO_INGREDIENTES_GLOBAL
  AS
SELECT
  E7SUCURSAL.NOMBRE AS SUCURSAL,
  E7INVENTARIO.ITEM_ID AS ID,
  E7INVENTARIO.CANTIDAD,
  E7INGREDIENTE.NOMBRE
FROM E7INVENTARIO@CDMX, E7INGREDIENTE@CDMX, E7SUCURSAL@CDMX
WHERE E7INVENTARIO.TIPO_ITEM = 'I'
      AND E7INGREDIENTE.ID = E7INVENTARIO.ITEM_ID
UNION
SELECT
  E7SUCURSAL.NOMBRE,
  E7INVENTARIO.ITEM_ID AS ID,
  E7INVENTARIO.CANTIDAD,
  E7INGREDIENTE.NOMBRE
FROM E7INVENTARIO@P_QRO, E7INGREDIENTE@P_QRO, E7SUCURSAL@P_QRO
WHERE E7INVENTARIO.TIPO_ITEM = 'I'
      AND E7INGREDIENTE.ID = E7INVENTARIO.ITEM_ID
      AND E7SUCURSAL.ID = E7INVENTARIO.SUCURSAL_ID AND E7SUCURSAL.ID = E7INVENTARIO.SUCURSAL_ID
UNION
SELECT
  E7SUCURSAL.NOMBRE,
  E7INVENTARIO.ITEM_ID AS ID,
  E7INVENTARIO.CANTIDAD,
  E7INGREDIENTE.NOMBRE
FROM E7INVENTARIO@SLP, E7INGREDIENTE@SLP, E7SUCURSAL@SLP
WHERE E7INVENTARIO.TIPO_ITEM = 'I'
      AND E7INGREDIENTE.ID = E7INVENTARIO.ITEM_ID
      AND E7SUCURSAL.ID = E7INVENTARIO.SUCURSAL_ID;
