CREATE OR REPLACE TRIGGER ACTULIZARGASTOS
AFTER UPDATE OR INSERT ON E7COMPRA
REFERENCING NEW AS NEW
FOR EACH ROW
  BEGIN
    INSERT INTO E7GASTO(ID, SUCURSAL_ID, TIPO_GASTO, GASTO_ID, FECHA_CREACION)
      VALUES (SEQ_GASTO.nextval, 3, 'P', :new.id, sysdate);
  END;
