CREATE OR REPLACE PROCEDURE DARBAJAEMPLEADO
  (
    e_nombre   IN VARCHAR2,
    e_apellido IN VARCHAR2
  ) AS
  BEGIN
    DELETE FROM E7EMPLEADO
    WHERE E7EMPLEADO.NOMBRE = e_nombre
    AND E7EMPLEADO.APELLIDO = e_apellido;
    COMMIT;
  END DARBAJAEMPLEADO;
