CREATE OR REPLACE PROCEDURE DARBAJAEMPLEADO
  (
    e_nombre   IN VARCHAR2,
    e_apellido IN VARCHAR2
  ) IS e_id NUMBER(5);
  BEGIN
    SELECT ID
    INTO e_id
    FROM E7EMPLEADO
    WHERE E7EMPLEADO.NOMBRE = e_nombre
          AND E7EMPLEADO.APELLIDO = e_apellido;
    DELETE FROM E7NOMINA
    WHERE E7NOMINA.EMPLEADO_ID = e_id;
    DELETE FROM E7EMPLEADO
    WHERE E7EMPLEADO.NOMBRE = e_nombre
          AND E7EMPLEADO.APELLIDO = e_apellido;
    COMMIT;
  END DARBAJAEMPLEADO;
